pipeline {
    agent any

    stages {
        stage('Build Docker Image') {
            steps {

                    sh 'docker compose build'

            }
            
        }

        stage('Run Docker Container') {
            steps {
                withCredentials([string(credentialsId: 'TTN_API_KEY', variable: 'TTN_API_KEY')]) {

                    sh 'docker compose -p mqtt up -d --force-recreate'
                }
            }
        }e
    }

}
