name: prod deployment

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: quantum_server
    concurrency:
      group: run_prod
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Write .env file
        run: echo "${{ secrets.QUANTUM_MQTT_ENV_PROD }}" > .env

      - name: Run Docker container
        run: |
          docker compose -p mqtt down
          docker compose -p mqtt up -d --build --force-recreate